typeset -gU cdpath fpath mailpath path

export EDITOR='nvim'
export PAGER='less'
export ERL_AFLAGS="-kernel shell_history enabled"

if [[ -z "$LANG" ]]; then
  export LANG='en_GB.UTF-8'
fi

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

cdpath=(
  $cdpath
  $HOME/dotfiles
  $HOME/Documents/fourth
)

path=(
  /usr/local/{bin,sbin}
  $path
)
