export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git/*"'

[ -f /usr/local/etc/profile.d/autojump.sh  ] && source /usr/local/etc/profile.d/autojump.sh

source $HOME/dotfiles/zsh/aliases.zsh
source $HOME/dotfiles/zsh/history.zsh
source $HOME/dotfiles/zsh/keybindings.zsh
