export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "modules/completion", from:prezto
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions", use:"zsh-autosuggestions.zsh"
zplug "themes/minimal", from:oh-my-zsh

if ! zplug check --verbose; then
    printf "Install zplug plugins? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

[ -s "$HOME/.asdf/asdf.sh" ] &&  . "$HOME/.asdf/asdf.sh"
[ -s "$HOME/.asdf/completions/asdf.bash" ] && . "$HOME/.asdf/completions/asdf.bash"

source "$HOME/dotfiles/zsh/aliases.zsh"
source "$HOME/dotfiles/zsh/functions.zsh"
source "$HOME/dotfiles/zsh/history.zsh"
source "$HOME/dotfiles/zsh/keybindings.zsh"
source "$HOME/dotfiles/zsh/navigation.zsh"
source "$HOME/dotfiles/zsh/fzf.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
